spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orderflow_db
    username: orderflow_user
    password: orderflow_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true